Update layout md plots
bigladder/dimes pull request #8
Opened 2024-05-08 18:04 UTC by nathancoliver

Below is a general list of changes:

- Defines plot format, including plot background color, and grid lines and border line color and line width.
- Automatically sets y-axis range. User currently does not have the ability to set the y-axis range.
- User can define plot title, and group plot lines into a legend group and provide a legend group name.
- Added units tests for legend_group and is_visible.

2024-05-09 15:16 UTC, nealkruis requested changes
@nathancoliver, these are all great changes! I have a few comments on the implementation that I'm happy to go over with you on a call.

2024-05-09 15:16 UTC, nealkruis commented on dimes/common.py
> +                                    legendgrouptitle={"text":display_data.legend_properties.legend_group},
This is a great addition!

2024-05-09 19:28 UTC, nathancoliver commented on dimes/common.py
> +        self.GREY = "rgba(128,128,128,0.3)"
I moved them.

2024-05-09 19:29 UTC, nathancoliver commented on dimes/common.py
> +        self.RANGE_BUFFER = 0.1
RANGE_BUFFER is now a module variable. Should I move this variable to within the function?

2024-05-09 19:30 UTC, nathancoliver commented on dimes/common.py
> +        self.GRID_LINE_WIDTH = 1.5
GRID_LINE_WIDTH is currently being used in four locations. It is now a module variable if that is okay.

2024-05-09 19:33 UTC, nathancoliver commented on dimes/timeseries.py
> +        self.figure.layout["title"] = plot_title
I'll try and work this out

2024-05-09 19:33 UTC, nathancoliver commented on dimes/common.py
> +    legend_group: Union[str, int, None] = None
Okay

2024-05-09 19:33 UTC, nathancoliver commented on dimes/common.py
> +    legend_group: Union[str, int, None] = None
It could be a year

2024-05-09 19:38 UTC, nathancoliver commented on dimes/common.py
> +        return [min_value - range_values*self.RANGE_BUFFER, max_value + range_values*self.RANGE_BUFFER]
In the acceptance criteria plots, I used a method to round up the max value to the nearest integer of five, and vise versa for the min value.  The tricky part will be in determining which nearest integer to round to, whether it's 1, 5, 100, etc.

2024-05-09 19:38 UTC, nathancoliver commented on dimes/common.py
> +                                    legendgrouptitle={"text":display_data.legend_properties.legend_group},
Thanks

2024-05-09 21:03 UTC, nathancoliver commented on dimes/common.py
> +        return [min_value - range_values*self.RANGE_BUFFER, max_value + range_values*self.RANGE_BUFFER]
Notes: set initial min and max values to positive inf and negative inf, respectively. Move set_axis_range to axis.

2024-05-10 18:28 UTC, nealkruis approved these changes

2024-05-10 18:28 UTC, merged